//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkYaklasimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseID { get; set; }
        public string CourseName { get; set; }
        public string Location { get; set; }
        public int TeacherID { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
